export const enslaved_default_list = [
  "id",
  "documented_name",
  "age",
  "gender",
  "height",
  "post_disembark_location__geo_location__name",
  "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase__geo_location__name",
  "voyage__voyage_itinerary__imp_principal_port_slave_dis__geo_location__name",
  "voyage__voyage_ship__ship_name",
  // "transactions__transaction__voyage__voyage_itinerary__imp_principal_place_of_slave_purchase__geo_location__name",
  // "transactions__transaction__voyage__voyage_itinerary__imp_principal_port_slave_dis__geo_location__name",
  // "transactions__transaction__voyage__voyage_ship__ship_name",
  // "skin_color",
  // "last_known_year_yyyy",
  // "transactions__transaction__place__geo_location__name",
  // "transactions__transaction__enslavers__enslaver_alias__identity__principal_alias",
  // "transactions__transaction__enslavers__role__role",
  // "transactions__transaction__source__full_ref",
];

export const enslaved_var_list = [
  "post_disembark_location__geo_location__name",
  "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase__geo_location__name",
  "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase__geo_location__location_type__name",
  "voyage__voyage_itinerary__imp_principal_region_of_slave_purchase__geo_location__location_type__name",
  "voyage__voyage_itinerary__imp_principal_region_of_slave_purchase__geo_location__name",
  "voyage__voyage_itinerary__imp_broad_region_of_slave_purchase__geo_location__location_type__name",
  "voyage__voyage_itinerary__imp_broad_region_of_slave_purchase__geo_location__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_place_of_slave_purchase__geo_location__location_type__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_place_of_slave_purchase__geo_location__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_region_of_slave_purchase__geo_location__location_type__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_region_of_slave_purchase__geo_location__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_broad_region_of_slave_purchase__geo_location__location_type__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_broad_region_of_slave_purchase__geo_location__name",
  "voyage__voyage_itinerary__imp_principal_region_slave_dis__geo_location__location_type__name",
  "voyage__voyage_itinerary__imp_principal_region_slave_dis__geo_location__name",
  "voyage__voyage_itinerary__imp_principal_port_slave_dis__geo_location__location_type__name",
  "voyage__voyage_itinerary__imp_principal_port_slave_dis__geo_location__name",
  "voyage__voyage_itinerary__imp_broad_region_slave_dis__geo_location__location_type__name",
  "voyage__voyage_itinerary__imp_broad_region_slave_dis__geo_location__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_region_slave_dis__geo_location__location_type__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_region_slave_dis__geo_location__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_port_slave_dis__geo_location__location_type__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_principal_port_slave_dis__geo_location__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_broad_region_slave_dis__geo_location__location_type__name",
  "transactions__transaction__voyage__voyage_itinerary__imp_broad_region_slave_dis__geo_location__name",
  "voyage__voyage_ship__ship_name",
  "transactions__transaction__voyage__voyage_ship__ship_name",
  "captive_status__name",
  "documented_name",
  "name_first",
  "name_second",
  "name_third",
  "modern_name",
  "editor_modern_names_certainty",
  "age",
  "gender",
  "height",
  "skin_color",
  "last_known_date",
  "last_known_date_dd",
  "last_known_date_mm",
  "last_known_year_yyyy",
  "dataset",
  "notes",
  "language_group",
  "transactions__transaction__date_yyyy",
  "transactions__transaction__amount",
  "transactions__transaction__place__geo_location__name",
  "transactions__transaction__enslavers__enslaver_alias__identity__principal_alias",
  //"transactions__transaction__enslavers__enslaver_alias__identity__principal_location__name", // invalid
  "transactions__transaction__enslavers__role__role",
  "transactions__transaction__text_ref",
  "transactions__transaction__source__full_ref",
];
